from django.db.models.signals import post_save, pre_save
from django.dispatch import receiver
from django.contrib.auth.models import User
from django.core.mail import send_mail
from django.conf import settings
from .models import Sale, Product

# --- FEATURE 1: LOW STOCK ALERT ---
@receiver(post_save, sender=Sale)
def check_stock_and_notify(sender, instance, created, **kwargs):
    if created:
        # Note: Depending on your model, you might need instance.product 
        # based on your Sale model fields
        try:
            # Finding the product by name from the Sale instance
            product = Product.objects.get(name=instance.product_name)
            threshold = 10 

            if product.stock <= threshold:
                subject = f"⚠️ LOW STOCK ALERT: {product.name}"
                message = (
                    f"SYSTEM ALERT: Inventory Depletion\n"
                    f"------------------------------\n"
                    f"Product: {product.name}\n"
                    f"Remaining Stock: {product.stock}\n"
                    f"Status: Please restock immediately.\n"
                    f"------------------------------\n"
                    f"Generated by Matrix POS"
                )
                
                send_mail(
                    subject,
                    message,
                    settings.EMAIL_HOST_USER,
                    ['vanshikababral@gmail.com'], 
                    fail_silently=False,
                )
                print(f"Inventory signal processed for {product.name}")
        except Product.DoesNotExist:
            print("Signal Error: Product not found in database")

# --- FEATURE 2: USER APPROVAL NOTIFICATION ---
@receiver(pre_save, sender=User)
def notify_user_on_approval(sender, instance, **kwargs):
    # Skip if this is a brand new user (no ID yet)
    if not instance.pk:
        return

    try:
        # Get the 'old' version of the user from the database
        old_instance = User.objects.get(pk=instance.pk)
    except User.DoesNotExist:
        return

    # If the manager flips 'is_active' from False to True
    if not old_instance.is_active and instance.is_active:
        subject = "🚀 Matrix Access Authorized"
        message = (
            f"Hello {instance.username},\n\n"
            f"Your system identity has been verified by the manager.\n"
            f"Your account is now ACTIVE and you may log in to the terminal.\n\n"
            f"Terminal Link: http://localhost:3000\n"
            f"------------------------------\n"
            f"Matrix Security Protocol"
        )
        
        send_mail(
            subject,
            message,
            settings.EMAIL_HOST_USER,
            [instance.email],
            fail_silently=False,
        )
        print(f"Approval email dispatched to {instance.email}")